version: '3.8'

services:
  foc-studio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foc_studio_oss
    restart: unless-stopped
    ports:
      - "1111:1111"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyACM0:/dev/ttyACM0"
    privileged: true
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=1111
